# Generated by Django 5.2.5 on 2025-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
